### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by danhanks** [dmachard/dnstap-receiver#38]
Hi, thanks for your work on this tool, it's very useful.

I'd like to use `dnstap_receiver` on a device that receives nearly 20k QPS at peak times. I've done some testing on the following test device:

32-core (hyperthreading) Intel E5-2630 @2.4Ghz. 
BIND 9.11.x, configured with dnstap to a unix socket
Running `dnstap_receiver` on the same device, polling the same unix socket

Using `dnsperf` to generate traffic to the server, I find that as I get up to around 1500 QPS or higher, `dnstap_receiver` is consuming most of a single CPU, and starts to lose requests in the statistics output. (E.g., If I send 100,000 queries to the server, only 70,000 or so are counted in the statistics. The higher I go, the more that is lost.

I'm running `dnstap_receiver -u </path/to/dnstap.sock> -p 6000 -c </path/to/config.file> -l 0.0.0.0`

Here's my config
```
web-api:
  # enable or disable
  enable: true
  # web api key
  api-key: changeme
  # basicauth login
  login: admin
  # basicauth password
  password: changeme
  # listening address ipv4 0.0.0.0 or ipv6 [::]
  local-address: 0.0.0.0
  # listing on port
  local-port: 8080
geoip:
  enable: false
output:
  stdout:
    enable: false
  file:
    enable: false
  metrics:
    enable: false
  tcp-socket:
    enable: false
  syslog:
    enable: false
  dnstap:
    enable: false
  kafka:
    enable: false
```

Not looking for any kind of output per se, mainly just interested in the stats that show up in the web api. End goal, I'm trying to get a comprehensive list of all names queried against my resolvers.

Do you have any suggestions to improve performance?

Thanks
